version: "1"

# Default environment is dev. You can add stage/prod later with their own secrets.
vars:
  RPC: ${{ env.L2_RPC_DEV }}
  PK: ${{ env.PRIVATE_KEY_DEV }}
  SAFE: ${{ env.SAFE_ADDRESS_DEV }}

jobs:
  deploy_dev:
    desc: Deploy Governance to OP Sepolia via Foundry
    steps:
      - name: Build
        run: |
          forge --version
          forge build -vvv

      - name: Deploy
        run: |
          export L2_RPC_DEV="${RPC}"
          export PRIVATE_KEY_DEV="${PK}"
          export SAFE_ADDRESS_DEV="${SAFE}"
          forge script script/DeployGovernance.s.sol \
            --rpc-url "$L2_RPC_DEV" \
            --private-key "$PRIVATE_KEY_DEV" \
            --broadcast -vvvv --slow | tee deploy.out

      - name: Capture Timelock
        run: |
          # Try to extract a 0x address from typical Foundry output lines
          TL=$(grep -Eo "0x[0-9a-fA-F]{40}" deploy.out | tail -1)
          echo "TIMELOCK_ADDRESS_DEV=$TL" | tee timelock.env

      - name: Upload artifacts
        run: |
          mkdir -p .codex-artifacts
          cp -r broadcast .codex-artifacts/ || true
          cp deploy.out .codex-artifacts/ || true
          cp timelock.env .codex-artifacts/ || true
