[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Let Foundry auto-pick the right compiler for each file pragma (e.g., ^0.8.25)
auto_detect_solc = true

evm_version = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "short"
