[profile.default]
src = "src"
test = "test"
out = "out"
libraries = []
solc_version = "0.8.25"
evmmode = "london"
optimizer = true
optimizer_runs = 600

remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]
