[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

# Remappings so imports like @openzeppelin/... work
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "short"
