[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
bytecode_hash = "ipfs"
cbor_metadata = false
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "short"
