name: ci-smoke
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke (Foundry build check)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Foundry (forge/cast) so commands exist on the runner
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Tooling sanity
        run: |
          forge --version
          cast --version

      # Ultra-light build to verify the repo is sane; fast and fails if config is broken
      - name: Forge build (smoke)
        run: forge build --sizes
