name: Smoke (Foundry build & tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: lib
          key: oz-forge-std-${{ runner.os }}-${{ hashFiles('foundry.toml') }}
          restore-keys: oz-forge-std-${{ runner.os }}-

      - name: Fetch OpenZeppelin & forge-std
        run: |
          set -e
          mkdir -p lib
          if [ ! -d lib/openzeppelin-contracts ]; then
            git clone --depth 1 --branch v5.0.2 https://github.com/OpenZeppelin/openzeppelin-contracts lib/openzeppelin-contracts
          fi
          if [ ! -d lib/forge-std ]; then
            git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
          fi
          ls -la lib

      - name: Tooling sanity
        run: forge --version && forge solc --version

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vv
