name: ci-smoke
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke (Foundry build check)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Tooling sanity
        run: |
          forge --version
          cast --version

      # ✅ Install deps so imports like @openzeppelin/... resolve
      - name: Install dependencies
        run: |
          mkdir -p lib
          forge install --no-commit OpenZeppelin/openzeppelin-contracts@v4.9.6

      # Optional: quick tree (helps if pathing is ever off)
      - name: Show tree (top level)
        run: ls -la

      - name: Forge build (smoke)
        run: forge build --sizes
