name: use-codex
on:
  workflow_dispatch:
    inputs:
      env:
        description: "dev | stage | prod"
        required: true
        type: choice
        options: [dev, stage, prod]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with: { version: nightly }
      - name: Build + quick tests
        run: |
          forge --version
          forge build
          forge test -vv || true   # don't block bootstrap if no tests
      - name: Codex plan (echo only for first run)
        run: echo "codex plan --repo ${{ github.event.repository.name }} --env ${{ inputs.env }} --version $GITHUB_SHA"
      - name: Deploy via Codex
        env:
          PRIVATE_KEY_DEV: ${{ secrets.PRIVATE_KEY_DEV }}
          PRIVATE_KEY_STAGE: ${{ secrets.PRIVATE_KEY_STAGE }}
          PRIVATE_KEY_PROD: ${{ secrets.PRIVATE_KEY_PROD }}
          BLOCK_EXPLORER_API_KEY: ${{ secrets.BLOCK_EXPLORER_API_KEY_DEV }}
        run: |
          codex deploy --repo ${{ github.event.repository.name }} --env ${{ inputs.env }} --version $GITHUB_SHA
      - name: Verify deployment
        run: |
          codex verify --repo ${{ github.event.repository.name }} --env ${{ inputs.env }}
